server:
  port: 8090
  servlet:
    context-path: /sku-service/api
spring:
  application:
    name: sw-sku-service
  datasource:
      url: jdbc:postgresql://localhost:5444/postgres
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
